const express=require('express')
const dotenv=require('dotenv').config()
const bodyParser=require('body-parser')
const cors=require('cors')
const mongoose=require('mongoose')
const user=require('./Models/user')
const signupUser=require('./Routes/signupUser') 
const loginUser=require('./Routes/loginUser')
const quiz=require('./Models/quiz')
const addQuiz=require('./Routes/addQuiz')
const getQuiz=require('./Routes/getQuiz')
const questionNumber=require('./Routes/getQuizNumber')
const incrementImpression=require('./Routes/incrementImpression')
const quizzes=require('./Routes/getQuizzes')
const editQuiz=require('./Routes/editQuiz')
const quizAnalysis=require('./Routes/getQuizAnalysis')
const updateQuizAnalysis=require('./Routes/updateQuizAnalysis')
const updateSelected=require('./Routes/updateSelectedOption')
const deleteQuiz=require('./Routes/deleteQuiz')


const app=express()
app.use(bodyParser.urlencoded({extended:false}))
app.use(bodyParser.json())
app.use(cors())


app.use('/',signupUser)
app.use('/',loginUser)
app.use('/',addQuiz)
app.use('/',getQuiz)
app.use('/',questionNumber)
app.use('/',incrementImpression)
app.use('/',quizzes)
app.use('/quizzes',editQuiz)
app.use('/quizzes',quizAnalysis)
app.use('/quizzes',updateQuizAnalysis)
app.use('/',updateSelected)
app.use('/quizzes',deleteQuiz)


app.listen(process.env.PORT,()=>{
    mongoose.connect(process.env.MONGODB_URL)
    .then(()=>console.log('connected to DB'))
    .catch((error)=>console.log(error))
    console.log(`server is running on http://localhost:${process.env.PORT}`)
})